namespace Cards
{
    public enum CardType
    {
        BubbleWand,
        CloneSphere,
        Divination,
        FastHands,
        FireArrow,
        FireBombOrb,
        FireMana,
        ForbiddenOrbA,
        ForbiddenOrbD,
        ForbiddenOrbE,
        ForbiddenOrbI,
        ForbiddenOrbO,
        ForbiddenOrbX,
        HailStorm,
        IceMana,
        Icicle,
        LightningStrike,
        ManaBlitz,
        ManaShield,
        OrbInlayedGauntlets,
        PowerSphere,
        RefreshOrb,
        ShieldBeetle,
        WardingRune,
    }
}
